# Summaries

## Libraries

In [4]:
import numpy as np
import pandas as pd

## Python

### $2^{3^2}$

In [1]:
2**3**2

512

### $\sqrt[2]{25}$

In [2]:
print(25 ** (1/2))

5.0


### $\sqrt[3]{64}$

In [3]:
print(64 ** (1/3))

3.9999999999999996


### Quotient and residue

In [1]:
22 // 6

3

In [2]:
22 % 6

4

### Tuple as dict key

In [3]:
tuple_as_dict_key = {
    (1, 2, 3): ['gold', 'silver coins'],
    (2, 4, 5.6): 'ship'
}

tuple_as_dict_key

{(1, 2, 3): ['gold', 'silver coins'], (2, 4, 5.6): 'ship'}

## Numpy

### Create arrays

In [5]:
np.array([1, 4, 5])

array([1, 4, 5])

In [7]:
np.array([[1, 4, 5], [2, 5, 7]])

array([[1, 4, 5],
       [2, 5, 7]])

In [8]:
np.array([(1, 4, 5), (2, 5, 7)])

array([[1, 4, 5],
       [2, 5, 7]])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.full((3, 2), 34)

array([[34, 34],
       [34, 34],
       [34, 34]])

In [18]:
# start, end - 1, step
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [21]:
# start, end, number of parts
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### Arrays info

#### Shape

In [23]:
np.array([1, 2, 3]).shape

(3,)

In [34]:
np.array([
    [1, 2, 3], 
    [4, 5, 6]
]).shape

(2, 3)

In [35]:
np.array([
    [[1, 2], [3, 4]], 
    [[5, 6], [7, 8]]
]).shape

(2, 2, 2)

#### Len

In [25]:
len(np.array([1, 2, 3]))

3

In [36]:
len(np.array([
    [1, 2, 3], 
    [4, 5, 6]
]))

2

In [37]:
len(np.array([
    [[1, 2], [3, 4]], 
    [[5, 6], [7, 8]]
]))

2

#### Ndim

In [27]:
np.array([1, 2, 3]).ndim

1

In [38]:
np.array([
    [1, 2, 3], 
    [4, 5, 6]
]).ndim

2

In [39]:
np.array([
    [[1, 2], [3, 4]], 
    [[5, 6], [7, 8]]
]).ndim

3

#### Size

In [41]:
np.array([1, 2, 3]).size

3

In [42]:
np.array([
    [1, 2, 3], 
    [4, 5, 6]
]).size

6

In [43]:
np.array([
    [[1, 2], [3, 4]], 
    [[5, 6], [7, 8]]
]).size

8

### Operations

#### Sum

In [44]:
np.array([1, 1, 1]) + np.array([2, 2, 2])

array([3, 3, 3])

In [46]:
np.add(np.array([1, 1, 1]), np.array([2, 2, 2]))

array([3, 3, 3])

In [50]:
np.array([1, 2, 3]).sum()

6

#### Subtract

In [48]:
np.array([1, 1, 1]) - np.array([2, 2, 2])

array([-1, -1, -1])

In [49]:
np.subtract(np.array([1, 1, 1]), np.array([2, 2, 2]))

array([-1, -1, -1])

#### Stats

In [52]:
np.array([1, 2, 3]).max()

3

In [53]:
np.array([1, 2, 3]).min()

1

In [55]:
# (1 + 2 + 3 + 4) / 4 = 10 / 4 = 2.5
np.array([1, 2, 3, 4]).mean()

2.5

In [61]:
# median(1, 2, 8, 3, 4) 
# order 1, 2, 3, 4, 8
# select the middle element 3
np.median(np.array([1, 2, 8, 3, 4]))

3.0

In [63]:
# median(1, 2, 8, 3, 4, 3.5) 
# order 1, 2, 3, 3.5, 4, 8
# calculate the mean of the elements in the middle (3 + 3.5) / 2 = 3.25
np.median(np.array([1, 2, 8, 3, 4, 3.5]))

3.25

## Pandas

### Create DataFrame

In [64]:
pd.DataFrame({
    'name': ['Ana', 'Bruno', 'César', 'Diego', 'Erika'],
	'age': [28, 33, 34, 23, 25],
	'height': [1.72, 1.69, 1.77, 1.79, 1.69],
	'has_linux': [True, False, False, True, True],
	'grade': [8, 7, 8, 10, 7]
})

name  age  height  has_linux  grade
0    Ana   28    1.72       True      8
1  Bruno   33    1.69      False      7
2  César   34    1.77      False      8
3  Diego   23    1.79       True     10
4  Erika   25    1.69       True      7

In [66]:
pd.DataFrame(
    [
        ['Ana', 'Bruno', 'César', 'Diego', 'Erika'],
        [28, 33, 34, 23, 25],
        [1.72, 1.69, 1.77, 1.79, 1.69],
        [True, False, False, True, True],
        [8, 7, 8, 10, 7]
    ],
    columns=["name", "age", "height", "has_linux", "grade"]
)

name    age height has_linux  grade
0   Ana  Bruno  César     Diego  Erika
1    28     33     34        23     25
2  1.72   1.69   1.77      1.79   1.69
3  True  False  False      True   True
4     8      7      8        10      7